name: Build and Deploy to OpenShift

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'  # or 'temurin', 'zulu', etc.
          java-package: 'jdk'
          architecture: 'x64'

      - name: Build WAR file
        run: mvn clean package

      - name: Build Docker image
        run: |
          docker build -t hello-world-liberty .
          docker images
      - name: Log in to Docker Registry
        env:
          REGISTRY: srikanth05061988/myfirstrepo  # e.g., 'docker.io' for Docker Hub
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login $REGISTRY --username $DOCKER_USERNAME --password-stdin
